steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [
      'build',
      '--no-cache',
      '-t',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '.',
      '-f',
      'Dockerfile'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    ]
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy
    args: [
      'run',
      'jobs',
      'deploy',
      '$_SERVICE_NAME',
      '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--region=$_DEPLOY_REGION',
      '--project=$PROJECT_ID',
      '--max-retries=0',
      '--tasks=1'
    ]
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: europe-west3
  _AR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: java-web-app
